apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: creditor
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "get"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["create"]
